// Generated by MistCSS, do not modify
import './Button.mist'

type Props = {
  children?: React.ReactNode
  size?: 'lg' | 'sm'
  danger?: boolean
} & JSX.IntrinsicElements['button']

export function Button({ children, size, danger, ...props }: Props) {
  return (
    <button {...props} className="button" data-size={size} data-danger={danger}>
      {children}
    </button>
  )
}
