// Generated by MistCSS, do not modify
import './Button.mist.css'

type Props = {
  children: React.ReactNode
  size: 'lg' | 'sm'
  danger: boolean
}

export function Button({ children, size, danger, ...props }: Props) {
  return (
    <button {...props} data-size={size} data-danger={danger}>
      {children}
    </button>
  )
}
