// Generated by MistCSS, do not modify
import './Foo.mist.css'

type FooProps = {
  children?: React.ReactNode
  fooSize?: 'lg' | 'sm'
  x?: boolean
} & JSX.IntrinsicElements['div']

export function Foo({ children, fooSize, x, ...props }: FooProps) {
  return (
    <div {...props} className="Foo" data-fooSize={fooSize} data-x={x}>
      {children}
    </div>
  )
}

type BarProps = {
  children?: React.ReactNode
  barSize?: 'lg'
  x?: boolean
} & JSX.IntrinsicElements['span']

export function Bar({ children, barSize, x, ...props }: BarProps) {
  return (
    <span {...props} className="Bar" data-barSize={barSize} data-x={x}>
      {children}
    </span>
  )
}

type BazProps = {
  children?: React.ReactNode
  
} & JSX.IntrinsicElements['p']

export function Baz({ children, ...props }: BazProps) {
  return (
    <p {...props} className="Baz">
      {children}
    </p>
  )
}
