import { Component, Components } from './parser.js'

function renderProps(component: Component): string {
  return Object.entries({
    children: 'ReactNode',
    ...component.data,
  })
    .map(([key, value]) => {
        if (Array.isArray(value)) {
            return `${key}?: ${value.map((v) => `'${v}'`).join(' | ')}`
        }

        if (typeof value === "string") {
            return `${key.startsWith('--') ? key.replace('--', '') : key}?: ${value.split(':')[0]}`
        }

        return `${key}?: boolean`
    })
    .map((line) => `  ${line}`)
    .join('\n')
}

function renderComponent(components: Components, name: string): string {
  const component = components[name]
  if (component === undefined) {
    return ''
  }

  const variables = Object.keys(component.data).filter(key => key.startsWith('--'));
  const hasVariables = variables.length > 0;

  return `type ${name}Props = {
${renderProps(component)}
} & JSX.IntrinsicElements['${component.tag}']

export function ${name}({ ${[
    'children',
    ...Object.keys(component.data).map(key => key.startsWith('--') ? key.replace('--', '') : key),
    '...props',
  ].join(', ')} }: ${name}Props) {
  return (
    <${[
      component.tag,
      '{...props}',
      `className="${component.className}"`,
      ...Object.keys(component.data).filter(key => !key.startsWith('--')).map((key) => `data-${key}={${key}}`),
      hasVariables ? `style={{
            ${variables.map(key => 
          (component.data[key] as string)?.includes(':') ? 
              `["${key}" as string]: \`\${${key.replace('--', '')}.includes("var(--") ? \`\${${key.replace('--', '')}}\` : \`${(component.data[key] as string).split(':')[1]}-\${${key.replace('--', '')}}\`}\`` 
              : `["${key}" as string]: \`\${${key.replace('--', '')}}\``)
          .join(',\r\n\t\t\t')}
        }}` : null,
    ].filter(item => item !== null).join("\r\n\t\t")}
    >
      {children}
    </${component.tag}>
  )
}
`
}

export function render(name: string, components: Components): string {
  return `// Generated by MistCSS, do not modify
import './${name}.mist.css'

import type { JSX, ReactNode } from 'react'

${Object.keys(components)
  .map((key) => renderComponent(components, key))
  .join('\n')
  .trim()}
`
}
