import assert from 'node:assert'
import fs from 'node:fs'
import test from 'node:test'
import os from 'node:os'

import {
  genToMistFilename,
  mistToGenFilename,
  safeCreateFile,
} from './writer.js'
import path from 'node:path'

test('genToMistFilename', () => {
  const actual = genToMistFilename('Foo.mist.tsx')
  const expected = 'Foo.mist.css'
  assert.strictEqual(actual, expected)
})

test('mistToGenFilename', () => {
  const actual = mistToGenFilename('Foo.mist.css')
  const expected = 'Foo.mist.tsx'
  assert.strictEqual(actual, expected)
})

test('safeCreateFile', () => {
  const dir = os.tmpdir()
  const mistCSS = path.join(dir, 'Foo.mist.css')
  const mistTSX = path.join(dir, 'Foo.mist.tsx')
  fs.writeFileSync(mistCSS, '@scope (.foo) { div:scope { color: red; } }')
  safeCreateFile(mistCSS)
  assert.ok(fs.existsSync(mistTSX), 'File not created')
  assert.ok(
    fs.readFileSync(mistTSX, 'utf8').includes('// Generated by MistCSS'),
    'Expected comment not found',
  )
})
